name: "Deploy to Server"

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:                    
        - name: Hola Mundo
          run: echo "Hola Mundo"
        
        - name: Actions        
          uses: actions/checkout@v4
        
        - name: listing dir
          run: ls -al

  second_job:
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: second Jobs steps
        run: echo "Second Job ${{ github.ref }}"

  third_job:
    if: ${{ github.ref == 'refs/heads/Development' }}
    needs: second_job
    runs-on: ubuntu-latest
    steps:
      - name: Third Job
        run: echo "Running on main branch"
