name: "My First Actions"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:                    
        - run: echo "Pulling the latest changes"
        - run: echo "Running migrations"
        - run: echo "Running binaries"
        - run: echo "Running tests"
        - run: echo "Deploying to production"
        - run: echo "Deployment complete"
