name: "Hola Actions"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:                    
        - run: echo "Hola Actions"
        - run: echo "haciendo algo"
        - run: echo "sigo haciendo algo"
        - run: echo "ya termine"
