name: "Deploy to Server"

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:                    
        - name: Hola Mundo
          run: echo "Hola Mundo"

jobs:
  second_job:
  runs-on: ubuntu-latest
  needs: first_job

  steps:
    - name: second Jobs steps
      run: echo "Second Job"
